"""
Notebook Generator
==================
Generates a complete, interactive, and directly runnable main_demo.ipynb.
"""

import json
from pathlib import Path


def create_demo_notebook() -> None:
    cells = [
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "# Scientific ML on Zero Budget: Training Real Models with Free Colab/Kaggle GPUs\n",
                "### SciPy India Conference Demonstration & Masterclass\n",
                "\n",
                "[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/)\n",
                "[![Zero Budget AI](https://img.shields.io/badge/Compute_Budget-$0.00_(Free_Tier)-brightgreen.svg)](https://github.com/)\n",
                "[![PyTorch 2.x](https://img.shields.io/badge/PyTorch-2.x_Supported-red.svg)](https://pytorch.org/)\n",
                "\n",
                "This interactive notebook demonstrates how to train real scientific machine learning models within the memory and time limits of **free-tier GPUs (Nvidia T4 16GB, Tesla P100)** without spending a single dollar on commercial cloud compute.\n",
                "\n",
                "---",
            ],
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## 1. Environment Diagnostics & Setup\n",
                "Let's detect our available GPU hardware, examine compute capability, and configure reproducible seeds.",
            ],
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Setup dependencies if running directly inside Google Colab\n",
                "import os, sys\n",
                "from pathlib import Path\n",
                "\n",
                "if 'google.colab' in sys.modules:\n",
                "    print('Running on Google Colab! Mounting drive and setting up repository...')\n",
                "    from google.colab import drive\n",
                "    drive.mount('/content/drive', force_remount=False)\n",
                "\n",
                "from reproducibility import seed_everything, capture_environment\n",
                "from utils.memory_profiler import MemoryTracker, print_gpu_hardware_summary\n",
                "\n",
                "seed_everything(42, deterministic=True)\n",
                "print_gpu_hardware_summary()\n",
            ],
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## 2. Scientific Problem: Spatio-Temporal Climate Forecasting\n",
                "We simulate a real-world multi-station atmospheric forecasting problem with physical dynamics:\n",
                "- Diurnal solar heating cycles (24h)\n",
                "- Coupled thermodynamic properties (temperature vs humidity)\n",
                "- Spatial covariance between neighboring weather monitoring stations\n",
                "- **Zero external downloads required:** Generated deterministically on disk.",
            ],
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "from utils.data_streaming import generate_synthetic_climate_data, MemmapScientificDataset, get_optimized_dataloader\n",
                "\n",
                "data_dir = Path('./sciml_data')\n",
                "feat_path, targ_path = generate_synthetic_climate_data(\n",
                "    output_dir=data_dir,\n",
                "    num_samples=4000,\n",
                "    seq_len=24,\n",
                "    num_stations=8,\n",
                "    num_features=4\n",
                ")\n",
                "\n",
                "# Zero-RAM memory mapped dataset\n",
                "dataset = MemmapScientificDataset(\n",
                "    features_path=feat_path,\n",
                "    targets_path=targ_path,\n",
                "    shape_x=(4000, 24, 8, 4),\n",
                "    shape_y=(4000, 8)\n",
                ")\n",
                "dataloader = get_optimized_dataloader(dataset, batch_size=32, shuffle=True)\n",
                "print(f'DataLoader initialized with {len(dataset)} scientific samples.')\n",
            ],
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## 3. Baseline Naive Training (FP32, Full Memory Load, No Checkpointing)\n",
                "Notice how standard FP32 operations and dense layers consume significant memory and throughput.",
            ],
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "import time, torch, torch.nn as nn\n",
                "from torch.optim import AdamW\n",
                "from main_demo import BaselineHeavyScientificModel\n",
                "from utils.training_utils import ScientificMetricsTracker\n",
                "\n",
                "device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')\n",
                "model_baseline = BaselineHeavyScientificModel().to(device)\n",
                "optimizer = AdamW(model_baseline.parameters(), lr=1e-3)\n",
                "loss_fn = nn.MSELoss()\n",
                "\n",
                "tracker = MemoryTracker(device=device)\n",
                "tracker.reset()\n",
                "metrics = ScientificMetricsTracker()\n",
                "t0 = time.perf_counter()\n",
                "\n",
                "model_baseline.train()\n",
                "for x_b, y_b in dataloader:\n",
                "    x_b, y_b = x_b.to(device), y_b.to(device)\n",
                "    optimizer.zero_grad()  # Naive zero_grad\n",
                "    preds = model_baseline(x_b)\n",
                "    loss = loss_fn(preds, y_b)\n",
                "    loss.backward()\n",
                "    optimizer.step()\n",
                "    metrics.update(preds, y_b, loss.item(), x_b.size(0))\n",
                "\n",
                "elapsed = time.perf_counter() - t0\n",
                "_, _, peak_vram = tracker.get_gpu_ram_mb()\n",
                "results_baseline = metrics.compute()\n",
                "print(f'Baseline FP32 Epoch Time: {elapsed:.2f}s | Throughput: {len(dataset)/elapsed:.1f} samples/s')\n",
                "if tracker.is_cuda:\n",
                "    print(f'Baseline Peak VRAM: {peak_vram:.1f} MB')\n",
                "print(f'Validation MSE: {results_baseline[\"mse\"]:.4f}')\n",
            ],
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## 4. Automatic Mixed Precision (AMP FP16) + GradScaler\n",
                "AMP accelerates tensor core operations and cuts activation memory footprint in half.",
            ],
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "from utils.training_utils import AMPTrainer\n",
                "\n",
                "model_amp = BaselineHeavyScientificModel().to(device)\n",
                "optimizer_amp = AdamW(model_amp.parameters(), lr=1e-3)\n",
                "amp_trainer = AMPTrainer(model=model_amp, optimizer=optimizer_amp, device=device, use_amp=True)\n",
                "\n",
                "tracker.reset()\n",
                "metrics.reset()\n",
                "t0 = time.perf_counter()\n",
                "\n",
                "model_amp.train()\n",
                "for x_b, y_b in dataloader:\n",
                "    loss, preds = amp_trainer.forward_backward_step(x_b, y_b, loss_fn=loss_fn)\n",
                "    metrics.update(preds, y_b, loss.item(), x_b.size(0))\n",
                "\n",
                "elapsed_amp = time.perf_counter() - t0\n",
                "_, _, peak_vram_amp = tracker.get_gpu_ram_mb()\n",
                "results_amp = metrics.compute()\n",
                "print(f'AMP FP16 Epoch Time: {elapsed_amp:.2f}s | Throughput: {len(dataset)/elapsed_amp:.1f} samples/s')\n",
                "if tracker.is_cuda:\n",
                "    print(f'AMP Peak VRAM: {peak_vram_amp:.1f} MB ({(1 - peak_vram_amp/peak_vram)*100:.1f}% VRAM saved!)')\n",
                "print(f'Validation MSE: {results_amp[\"mse\"]:.4f}')\n",
            ],
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## 5. Gradient Accumulation (Simulating Batch 128 on 16GB GPU)\n",
                "Achieve enterprise-grade mini-batch dynamics on a single free GPU by accumulating gradients across micro-steps.",
            ],
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "from utils.training_utils import GradientAccumulator\n",
                "\n",
                "model_accum = BaselineHeavyScientificModel().to(device)\n",
                "optimizer_accum = AdamW(model_accum.parameters(), lr=1e-3)\n",
                "accum_steps = 4  # Micro batch 32 * 4 = Effective Batch 128\n",
                "accumulator = GradientAccumulator(accumulation_steps=accum_steps)\n",
                "trainer_accum = AMPTrainer(model=model_accum, optimizer=optimizer_accum, device=device, use_amp=True)\n",
                "\n",
                "total_batches = len(dataloader)\n",
                "model_accum.train()\n",
                "for idx, (x_b, y_b) in enumerate(dataloader):\n",
                "    should_step = accumulator.should_step(idx, total_batches)\n",
                "    loss, preds = trainer_accum.forward_backward_step(\n",
                "        x_b, y_b, loss_fn=loss_fn,\n",
                "        accumulate_grad=(not should_step),\n",
                "        accumulation_steps=accum_steps\n",
                "    )\n",
                "\n",
                "print(f'Successfully trained with Effective Batch Size: {32 * accum_steps} within Micro-Batch 32 VRAM!')\n",
            ],
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## 6. Resilient Atomic Checkpointing\n",
                "Test atomic saving and state recovery to survive unexpected Colab disconnects without corrupting files.",
            ],
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "from utils.checkpoint_manager import CheckpointManager\n",
                "from main_demo import EfficientScientificModel\n",
                "\n",
                "ckpt_dir = Path('./sciml_checkpoints')\n",
                "manager = CheckpointManager(checkpoint_dir=ckpt_dir, project_name='sciml_climate')\n",
                "\n",
                "model_save = EfficientScientificModel().to(device)\n",
                "opt_save = AdamW(model_save.parameters(), lr=1e-3)\n",
                "\n",
                "# Save checkpoint\n",
                "saved_file = manager.save(model_save, opt_save, epoch=1, metric_val=0.142, is_best=True)\n",
                "print(f'Saved atomic checkpoint to: {saved_file}')\n",
                "\n",
                "# Simulate recovery\n",
                "model_resumed = EfficientScientificModel().to(device)\n",
                "resumed_epoch, best_metric, _ = manager.load_latest(model_resumed, device=device)\n",
                "print(f'Resumed successfully! Epoch: {resumed_epoch}, Metric: {best_metric:.4f}')\n",
            ],
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## 7. Efficient Model Architecture (Depthwise Separable Convolutions + SE Blocks)\n",
                "Cutting parameter count by >80% and inference latency by >3x.",
            ],
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "model_eff = EfficientScientificModel().to(device)\n",
                "opt_eff = AdamW(model_eff.parameters(), lr=1e-3)\n",
                "trainer_eff = AMPTrainer(model=model_eff, optimizer=opt_eff, device=device, use_amp=True)\n",
                "\n",
                "t0 = time.perf_counter()\n",
                "metrics.reset()\n",
                "model_eff.train()\n",
                "for x_b, y_b in dataloader:\n",
                "    loss, preds = trainer_eff.forward_backward_step(x_b, y_b, loss_fn=loss_fn)\n",
                "    metrics.update(preds, y_b, loss.item(), x_b.size(0))\n",
                "\n",
                "elapsed_eff = time.perf_counter() - t0\n",
                "res_eff = metrics.compute()\n",
                "print(f'Efficient Model Epoch Time: {elapsed_eff:.2f}s | Throughput: {len(dataset)/elapsed_eff:.1f} samples/s')\n",
                "print(f'Validation MSE: {res_eff[\"mse\"]:.4f}')\n",
            ],
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## 8. Benchmark Visualizations & Compute Savings\n",
                "Displaying our 4-panel publication-grade benchmark comparisons.",
            ],
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "from benchmark_results import generate_benchmark_plots, print_benchmark_tables\n",
                "from IPython.display import Image, display\n",
                "\n",
                "print_benchmark_tables()\n",
                "generate_benchmark_plots('benchmark_comparison.png')\n",
                "display(Image('benchmark_comparison.png'))\n",
            ],
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## 9. Compute Disclosure & Reproducibility Citation\n",
                "Generate academic badge and disclosure statement for publication.",
            ],
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "from reproducibility import generate_compute_badge\n",
                "from IPython.display import Markdown\n",
                "\n",
                "badge_md = generate_compute_badge(platform_name='Google Colab Free (T4)', training_hours=0.5, cloud_cost_saved_usd=1.53)\n",
                "display(Markdown(badge_md))\n",
            ],
        },
    ]

    notebook_data = {
        "cells": cells,
        "metadata": {
            "kernelspec": {
                "display_name": "Python 3",
                "language": "python",
                "name": "python3",
            },
            "language_info": {
                "codemirror_mode": {"name": "ipython", "version": 3},
                "file_extension": ".py",
                "mimetype": "text/x-python",
                "name": "python",
                "nbconvert_exporter": "python",
                "pygments_lexer": "ipython3",
                "version": "3.10.0",
            },
        },
        "nbformat": 4,
        "nbformat_minor": 5,
    }

    nb_path = Path("main_demo.ipynb")
    with open(nb_path, "w", encoding="utf-8") as f:
        json.dump(notebook_data, f, indent=2)
    print(f"Generated clean notebook at: {nb_path.resolve()}")


if __name__ == "__main__":
    create_demo_notebook()
